export { AppRouters } from './ui/AppRouters'
export { ERoutePath } from './config/routeConfig'
export { ICREATE_MODULE_Params } from './config/routeConfig'
export { ICREATE_LESSON_Params } from './config/routeConfig'
export { IEDIT_LESSON_Params } from './config/routeConfig'
export { ILAST_ID_Params } from './config/routeConfig'
export { IABOUT_COURSE_Params } from './config/routeConfig'
