# Generated by Django 4.2.1 on 2023-06-05 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('course', '0002_course_image_course_rating_course_teacher_and_more'),
        ('file_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetasks',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='filetasks',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='filetasks',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_tasks.filetasksgrade'),
        ),
        migrations.AddField(
            model_name='filetasks',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filetasksanswer',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filetasksanswer',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='filetasksanswer',
            name='file_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_tasks.filetasks'),
        ),
        migrations.AddField(
            model_name='filetasksanswer',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
        migrations.AddField(
            model_name='filetasksgrade',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filetasksgrade',
            name='file_task_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_tasks.filetasks'),
        ),
        migrations.AddField(
            model_name='filetasksgrade',
            name='grade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='filetasksgrade',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
    ]
