# Generated by Django 4.2.1 on 2023-06-15 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_tasks', '0002_alter_filetasksanswer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetasksanswer',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
