# Generated by Django 4.2.1 on 2023-06-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_tasks', '0002_filetasks_course_filetasks_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetasksanswer',
            old_name='file_id',
            new_name='file_task',
        ),
        migrations.RenameField(
            model_name='filetasksgrade',
            old_name='file_task_id',
            new_name='file_task',
        ),
        migrations.RemoveField(
            model_name='filetasks',
            name='grade',
        ),
    ]
