# Generated by Django 4.2.1 on 2023-06-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_tasks', '0004_filetasksanswer_list_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetasksgrade',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
