# Generated by Django 4.2.1 on 2023-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_tasks', '0006_filetasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetasks',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
