# Generated by Django 4.2.1 on 2023-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_tasks', '0007_alter_filetasks_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetasksanswer',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
