# Generated by Django 4.2.1 on 2023-06-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_tasks', '0010_alter_filetasksanswer_is_late'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetasks',
            name='deadline',
        ),
    ]
