# Generated by Django 4.2.1 on 2023-06-23 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_modules', '0003_alter_listmodules_number'),
        ('file_tasks', '0011_remove_filetasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetasksanswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='filetasksanswer',
            name='file_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_tasks.filetasks'),
        ),
        migrations.AlterField(
            model_name='filetasksanswer',
            name='list_modules',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules'),
        ),
        migrations.AlterField(
            model_name='filetasksgrade',
            name='file_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_tasks.filetasks'),
        ),
        migrations.AlterField(
            model_name='filetasksgrade',
            name='grade',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
