# Generated by Django 4.2.1 on 2023-06-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tasks', '0002_testansweroptions_course_testgrade_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestionanswer',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='testquestionanswer',
            name='test_task',
        ),
        migrations.AddField(
            model_name='testansweroptions',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testansweroptions',
            name='option',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testtasks',
            name='questions',
            field=models.ManyToManyField(to='test_tasks.testquestionanswer'),
        ),
    ]
