# Generated by Django 4.2.1 on 2023-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tasks', '0006_alter_testtasks_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtasks',
            name='questions',
            field=models.ManyToManyField(blank=True, to='test_tasks.testquestionanswer'),
        ),
    ]
