# Generated by Django 4.2.1 on 2023-06-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tasks', '0007_alter_testtasks_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgrade',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
