# Generated by Django 4.2.1 on 2023-06-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image_course_rating_course_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cat',
            new_name='category',
        ),
    ]
