# Generated by Django 4.2.1 on 2023-06-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teachers_category'),
        ('categories', '0001_initial'),
        ('course', '0003_rename_cat_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
