# Generated by Django 4.2.1 on 2023-06-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_modules', '0002_listmodules_file_task_id_listmodules_lecture_id_and_more'),
        ('course', '0004_alter_course_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='list_module',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules'),
        ),
    ]
