# Generated by Django 4.2.1 on 2023-06-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_category_alter_course_image_and_more'),
        ('course', '0005_course_list_module'),
    ]

    operations = [
    ]
