# Generated by Django 4.2.1 on 2023-06-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
