# Generated by Django 4.2.1 on 2023-06-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_cat_course_category'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.category'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='patronymic',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='surname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
