# Generated by Django 4.2.1 on 2023-06-23 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_name_category_title'),
        ('teachers', '0003_teachers_age_teachers_country_teachers_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='patronymic',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='surname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
