# Generated by Django 4.2.1 on 2023-06-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='admin_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Super Admin')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='admins',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='admins',
            name='patronymic',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='admins',
            name='surname',
            field=models.CharField(max_length=40),
        ),
    ]
