# Generated by Django 4.2.1 on 2023-06-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_admins_admin_type_alter_admins_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.EmailField(max_length=60),
        ),
    ]
