# Generated by Django 4.2.1 on 2023-06-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_admins_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='email',
        ),
    ]
