# Generated by Django 4.2.1 on 2023-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_remove_admins_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='patronymic3',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
