# Generated by Django 4.2.1 on 2023-06-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_admins_patronymic3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='patronymic3',
        ),
    ]
