# Generated by Django 4.2.1 on 2023-06-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_tasks', '0010_remove_testtasks_deadline'),
        ('file_tasks', '0012_alter_filetasksanswer_file_and_more'),
        ('lectures', '0001_initial'),
        ('list_modules', '0003_alter_listmodules_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodules',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listmodules',
            name='file_task_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_tasks.filetasks'),
        ),
        migrations.AlterField(
            model_name='listmodules',
            name='lecture_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.lectures'),
        ),
        migrations.AlterField(
            model_name='listmodules',
            name='number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='listmodules',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='listmodules',
            name='test_task_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_tasks.testtasks'),
        ),
    ]
