# Generated by Django 4.2.1 on 2023-06-04 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.DateField(default=datetime.date.today)),
                ('file', models.FileField(upload_to='uploads/')),
                ('email', models.EmailField(max_length=255)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.course')),
                ('student', models.ManyToManyField(to='students.students')),
            ],
        ),
    ]
