# Generated by Django 4.2.1 on 2023-06-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_cat_course_category'),
        ('students', '0003_alter_students_email'),
        ('certificates', '0002_remove_certificates_name_certificates_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='student',
        ),
        migrations.AddField(
            model_name='certificates',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
            preserve_default=False,
        ),
    ]
