# Generated by Django 4.2.1 on 2023-06-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_user_students_student'),
        ('certificates', '0004_alter_certificates_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
    ]
