# Generated by Django 4.2.1 on 2023-06-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_user_students_student'),
        ('certificates', '0006_alter_certificates_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
            preserve_default=False,
        ),
    ]
