# Generated by Django 4.2.1 on 2023-06-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list_modules', '0002_listmodules_deadline'),
        ('course', '0007_course_syllabus'),
        ('students', '0004_students_favorite_alter_students_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('list_modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
