# Generated by Django 4.2.1 on 2023-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grades_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='module_type',
            field=models.CharField(choices=[('1', 'lecture'), ('2', 'test task'), ('3', 'file task')], default='1', max_length=1),
        ),
    ]
