# Generated by Django 4.2.1 on 2023-06-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintickets',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admintickets',
            name='theme',
            field=models.CharField(blank=True, choices=[('1', 'Забыл пароль'), ('2', 'Смена курса '), ('3', 'Не работает ')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='studenttickets',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studenttickets',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachertickets',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unauthorizedtickets',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='unauthorizedtickets',
            name='theme',
            field=models.CharField(blank=True, choices=[('1', 'Забыл пароль'), ('2', 'Не могу войти '), ('3', 'Не работает ')], default='3', max_length=1),
        ),
    ]
