# Generated by Django 4.2.1 on 2023-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0002_alter_admintickets_answer_alter_admintickets_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintickets',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttickets',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='teachertickets',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='unauthorizedtickets',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
