# Generated by Django 4.2.1 on 2023-06-10 16:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_merge_20230610_2204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_comments_course_comments_data_comments_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='data',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
