# Generated by Django 4.2.1 on 2023-06-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image_course_rating_course_teacher_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='course.course'),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='patronymic',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='surname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
