# Generated by Django 4.2.1 on 2023-06-13 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_user_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='students',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='resume',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='university',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
