# Generated by Django 4.2.1 on 2023-06-16 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_course_syllabus'),
        ('students', '0003_students_age_students_country_students_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='favorite',
            field=models.ManyToManyField(related_name='student_favorite', to='course.course'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
