# Generated by Django 4.2.1 on 2023-06-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_syllabus'),
        ('students', '0004_students_favorite_alter_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='student_favorite', to='course.course'),
        ),
    ]
