---
name: Build and Push  Images to Docker Hub
on:
  push:
    branches: [master]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lmscasecup_nginx
      PROJECT_ID: lmsproject-390908
      DJANGO_DEFAULT_FROM_EMAIL: ${{ secrets.DJANGO_DEFAULT_FROM_EMAIL }}
      DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}
      DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_SOCIAL_AUTH_GITHUB_SECRET: ${{ secrets.DJANGO_SOCIAL_AUTH_GITHUB_SECRET }}
      DJANGO_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{ secrets.DJANGO_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
      DJANGO_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{ secrets.DJANGO_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Frontend Build
        working-directory: ./frontend
        run: |
          touch .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env
          cat .env
          npm install 
          npm run build:prod

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Backend Docker image
        working-directory: ./backend/lmssite/
        run: |
          ls
          docker build -t aligan/lmscasecup-backend . --file ./Dockerfile --tag backend:$(date +%s)

      - name: Docker Push
        run: docker push aligan/lmscasecup-backend

      - name: Build the Nginx Docker image
        run: docker build -t aligan/lmscasecup-nginx . --file ./Dockerfile --tag nginx:$(date +%s)

      - name: Docker Push
        run: docker push aligan/lmscasecup-nginx
