---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [master]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NGINX: lmscasecup_nginx
      IMAGE_BACKEND: lmscasecup_backend
      PROJECT_ID: lmsproject-390908
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Frontend Build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        working-directory: ./frontend
        run: |
          npm install 
          npm run build:prod

      - name: Build Docker
        env:
          DJANGO_DEFAULT_FROM_EMAIL: ${{ secrets.DJANGO_DEFAULT_FROM_EMAIL }}
          DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}
          DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_SOCIAL_AUTH_GITHUB_SECRET: ${{ secrets.DJANGO_SOCIAL_AUTH_GITHUB_SECRET }}
          DJANGO_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{ secrets.DJANGO_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
          DJANGO_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{ secrets.DJANGO_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
        run: |
          docker-compose build

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker images
          docker tag $IMAGE_NGINX:latest gcr.io/$PROJECT_ID/$IMAGE_NGINX:latest
          docker tag $IMAGE_NGINX:latest gcr.io/$PROJECT_ID/$IMAGE_NGINX:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NGINX:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NGINX:$GIT_TAG

          docker tag $IMAGE_BACKEND:latest gcr.io/$PROJECT_ID/$IMAGE_BACKEND:latest
          docker tag $IMAGE_BACKEND:latest gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_BACKEND:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$GIT_TAG

      # - name: Push Docker Image to Artifact Registry
      #   env:
      #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      #   run: |-
      #     docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
      #     docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
      #     docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
      #     docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
